# Advanced NumPy (Pages 473-505)

In [2]:
import numpy as np

## A.1 ndarray Object Internals

In [3]:
rng = np.random.default_rng(seed=12345)

In [4]:
np.ones((10, 5)).shape

(10, 5)

In [5]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

## NumPy Data Type Hierarchy

In [6]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [7]:
np.issubdtype(floats.dtype, np.floating)

True

In [ ]:
np.float64.mro()

In [8]:
np.issubdtype(ints.dtype, np.number)

True

## A.2 Advanced Array Manipulation

### Reshaping Arrays

In [9]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C Versus FORTRAN Order

In [16]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
arr = rng.standard_normal((5, 2))
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

In [24]:
first, second, third = np.split(arr, [1, 3])
first

array([[-1.42382504,  1.26372846]])

In [25]:
second

array([[-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465]])

In [26]:
third

array([[-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

### Stacking helpers: r_ and c_

In [27]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = rng.standard_normal((3, 2))
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 2.34740965,  0.96849691],
       [-0.75938718,  0.90219827],
       [-0.46695317, -0.06068952]])

In [28]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 2.34740965,  0.96849691,  3.        ],
       [-0.75938718,  0.90219827,  4.        ],
       [-0.46695317, -0.06068952,  5.        ]])

In [29]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating Elements: tile and repeat

In [30]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [31]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [ ]:
arr.repeat([2, 3, 4])

In [ ]:
arr = rng.standard_normal((2, 2))
arr

In [ ]:
arr.repeat(2, axis=0)

In [ ]:
arr.repeat([2, 3], axis=0)

In [ ]:
arr.repeat([2, 3], axis=1)

In [ ]:
arr

In [ ]:
np.tile(arr, 2)

In [ ]:
arr

In [ ]:
np.tile(arr, (2, 1))

In [1]:
arr

NameError: name 'arr' is not defined

In [ ]:
np.tile(arr, (3, 2))

### Fancy Indexing Equivalents: take and put

In [ ]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

In [ ]:
arr.take(inds)

In [ ]:
arr.put(inds, 42)
arr

In [ ]:
arr.put(inds, [40, 41, 42, 43])
arr

In [ ]:
inds = [2, 0, 2, 1]
arr = rng.standard_normal((2, 4))
arr

In [ ]:
arr.take(inds, axis=1)

## A.3 Broadcasting

In [ ]:
arr = np.arange(5)
arr
arr * 4

In [ ]:
arr = rng.standard_normal((4, 3))
arr.mean(0)

In [ ]:
demeaned = arr - arr.mean(0)
demeaned

In [ ]:
demeaned.mean(0)

In [ ]:
arr

In [ ]:
row_means = arr.mean(1)
row_means.shape

In [ ]:
row_means.reshape((4, 1))

In [ ]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

In [ ]:
arr - arr.mean(1).reshape((4, 1))

In [ ]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

In [ ]:
arr_1d = rng.standard_normal(3)
arr_1d[:, np.newaxis]

In [ ]:
arr_1d[np.newaxis, :]

In [ ]:
arr = rng.standard_normal((3, 4, 5))
depth_means = arr.mean(2)
depth_means

In [ ]:
depth_means.shape

In [ ]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

In [ ]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]
demean_axis(arr, 0)

In [ ]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

In [ ]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

In [ ]:
arr[:2] = [[-1.37], [0.509]]
arr

## A.4 Advanced ufunc Usage

### ufunc Instance Methods

In [ ]:
arr = np.arange(10)
np.add.reduce(arr)

In [ ]:
arr.sum()

In [ ]:
my_rng = np.random.default_rng(12346)  # for reproducibility
arr = my_rng.standard_normal((5, 5))
arr

In [ ]:
arr[::2].sort(1) # sort a few rows

In [ ]:
arr[:, :-1] < arr[:, 1:]

In [ ]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

In [ ]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

In [ ]:
arr = np.arange(3).repeat([1, 2, 2])
arr

In [ ]:
np.multiply.outer(arr, np.arange(5))

In [ ]:
x, y = rng.standard_normal((3, 4)), rng.standard_normal(5)
result = np.subtract.outer(x, y)
result.shape

In [ ]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

In [ ]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

In [ ]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

### Writing New ufuncs in Python

In [ ]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

In [ ]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

In [ ]:
arr = rng.standard_normal(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

## A.5 Structured and Record Arrays

In [ ]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

In [ ]:
sarr[0]

In [ ]:
sarr[0]['y']

In [ ]:
sarr['x']

In [ ]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

In [ ]:
arr[0]['x']

In [ ]:
arr['x']

In [ ]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

In [ ]:
data['y']

In [ ]:
data['x']['a']

## A.6 More About Sorting

In [ ]:
arr = rng.standard_normal(6)
arr.sort()
arr

In [ ]:
arr = rng.standard_normal((3, 5))
arr

In [ ]:
arr[:, 0].sort()  # Sort first column values in place
arr

In [ ]:
arr = rng.standard_normal(5)
arr

In [ ]:
np.sort(arr)

In [ ]:
arr

In [ ]:
arr = rng.standard_normal((3, 5))
arr

In [ ]:
arr.sort(axis=1)

In [ ]:
arr

In [ ]:
arr[:, ::-1]

### Indirect Sorts: argsort and lexsort

In [ ]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

In [ ]:
values[indexer]

In [ ]:
arr = rng.standard_normal((3, 5))
arr[0] = values
arr

In [ ]:
arr[:, arr[0].argsort()]

In [ ]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

In [ ]:
list(zip(last_name[sorter], first_name[sorter]))

### Alternative Sort Algorithms

In [ ]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
                   '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer

In [ ]:
values.take(indexer)

### Partially Sorting Arrays

In [ ]:
rng = np.random.default_rng(12345)
arr = rng.standard_normal(20)
arr

In [ ]:
np.partition(arr, 3)

In [ ]:
indices = np.argpartition(arr, 3)
indices

In [ ]:
arr.take(indices)

### numpy.searchsorted: Finding Elements in a Sorted Array

In [ ]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

In [ ]:
arr.searchsorted([0, 8, 11, 16])

In [ ]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

In [ ]:
arr.searchsorted([0, 1], side='right')

In [ ]:
data = np.floor(rng.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

In [ ]:
labels = bins.searchsorted(data)
labels

Note: For the pandas part, assuming pandas is imported

In [ ]:
import pandas as pd
pd.Series(data).groupby(labels).mean()

## A.7 Writing Fast NumPy Functions with Numba

In [ ]:
# Note: Numba may not be installed, but for the notebook
try:
    import numba as nb
except ImportError:
    print("Numba not available")
    nb = None

In [ ]:
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [ ]:
x = rng.standard_normal(10_000_000)
y = rng.standard_normal(10_000_000)
%timeit mean_distance(x, y)
%timeit (x - y).mean()

In [ ]:
if nb is not None:
    numba_mean_distance = nb.jit(mean_distance)
    %timeit numba_mean_distance(x, y)

### Creating Custom numpy.ufunc Objects with Numba

In [ ]:
if nb is not None:
    from numba import vectorize
    @vectorize
    def nb_add(x, y):
        return x + y
    x = np.arange(10)
    nb_add(x, x)
    nb_add.accumulate(x, 0)

## A.8 Advanced Array Input and Output

### Memory-Mapped Files

In [ ]:
# Note: This will create a file 'mymmap', be careful with disk space
# mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
# For demo, use smaller size
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(5, 5))
mmap

In [ ]:
section = mmap[:3]
section[:] = rng.standard_normal((3, 5))
mmap.flush()
mmap

In [ ]:
del mmap
mmap = np.memmap('mymmap', dtype='float64', shape=(5, 5))
mmap

In [ ]:
# Clean up
del mmap
import os
os.remove('mymmap')

## A.9 Performance Tips

In [ ]:
arr_c = np.ones((100, 10000), order='C')
arr_f = np.ones((100, 10000), order='F')
arr_c.flags

In [ ]:
arr_f.flags